[default]
debug = true

[default.logging]
level = "INFO"
file_enabled = true
console_enabled = false  # 关闭控制台输出
max_file_size = 10485760  # 10MB
backup_count = 5

[default.openai]
debug_enabled = true
log_requests = true
log_responses = true
log_level = "DEBUGE"
log_to_file = true
log_to_console = false  # 关闭控制台输出

[default.llm]
base_url = "https://api.siliconflow.cn/v1"
api_key = "@format {env[LLM_API_KEY]}"
model = "@format {env[LLM_MODEL]}"

[default.jina]
api_key = "@format {env[JINA_API_KEY]}"
search_base_url = "https://s.jina.ai/"
web_base_url = "https://r.jina.ai/"

[default.multilingual]
# Default language for the system (en, zh, es, fr, ja)
default_language = "en"
# Enable automatic language detection from user input
auto_detect = true
# Fallback to default language when requested language is not supported
fallback_enabled = true
# Supported languages (can be customized to enable/disable specific languages)
supported_languages = ["en", "zh", "es", "fr", "ja"]

[default.vector_service]
# Vector service configuration for tool recommendation
base_url = "http://nodeport.sensedeal.vip:32421"
timeout = 30

